spring:
  profiles:
#    active: "development"

  jpa :
      show-sql : true
  properties :
      hibernate :
              format_sql: true

  h2:
    console:
      enabled: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
  datasource:
    username: user
    password: user
    url: jdbc:h2:mem:curae_db;
    driver-class-name: org.h2.Driver

server:
  error:
    include-stacktrace: NEVER